name = "suiradynamics-cotizaciones-e-inventario"
main = ".open-next/worker.js"
compatibility_date = "2024-09-18"

[vars]
# Aquí puedes dejar espacio si necesitas variables globales extra, 
# pero ya las tienes configuradas en el panel de Cloudflare.

[[upload.rules]]
globs = ["**/*.wasm"]
fallthrough = true

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
